export const LOADING_SEARCH = "LOADING_SEARCH"
export const SUCCESS_SEARCH = "SUCCESS_SEARCH"
export const FAIL_SEARCH = "FAIL_SEARCH"
export const SEARCHING = "SEARCHING"

export const LOADING_PRODUCTS = "LOADING_PRODUCTS"
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS"
export const FAIL_PRODUCTS = "FAIL_PRODUCTS"

export const LOADING_PRODUCT = "LOADING_PRODUCT"
export const SUCCESS_PRODUCT = "SUCCESS_PRODUCT"
export const FAIL_PRODUCT = "FAIL_PRODUCT"
